//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Batalla.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//

package modelo;


public class Batalla extends Nave {
}
