//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ElementoDelEspacio.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//


package modelo;

public abstract class ElementoDelEspacio extends Juego{
	
	protected String nombre;
	protected int personas;
	
	
	public void avanzarTurno() {
	
	}
}
