//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EstadoNave.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//

package modelo;


public class EstadoNave {
	private boolean enTransito;
	private boolean Estacionado;
	public void Operation1() {
	
	}
}
