//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Flota.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//

package modelo;

import java.util.*;

public class Flota {
	private List<Nave> naves;
	private Planeta destino;
	private Planeta origen;
	
	public void viajarAlPlaneta(String planeta) {
		
	}
	
	public void crearNaveDeBatalla(){
		naves.add(new Batalla());
	}
	
	public void crearNaveDeTransporte(){
		naves.add(new Transporte());
	}
	
	public void crearNaveDestructor(){
		naves.add(new Destructor());
	}
	
	
	
	
}
