//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Juego.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//


package modelo;

import java.util.*;

public class Juego {
	protected int nroTurno;
	private List<ElementoDelEspacio> elementos;
	
	
	
	public void avanzarTurno() {
	
	}
	
	public void inicializarEscenario() {
	
	}
	
	public int getNroTurno() {
		return nroTurno;
	}

	public void setNroTurno(int nroTurno) {
		this.nroTurno = nroTurno;
	}
	
	
}
