//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nave.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//


package modelo;

public class Nave extends ElementoDelEspacio {
	private float velocidad;
	private int nivelAtaque;
	private int nivelDefensa;
	

	
	public void avanzarTurno() {
	
	}
}
