//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Planeta.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//

package modelo;

import java.util.*;

public class Planeta extends ElementoDelEspacio {
	private int cantidadTorretas;
	private int velocidadCrecimiento;
	private int velocidadProduccion;
	
	private List<Flota> flota;
	
	private boolean aumentandoProduccion;
	private boolean produciendoNaveDeBatalla;
	private boolean produciendoNaveDeTransporte;
	private boolean produciendoNaveDestructor;
	private boolean produciendoTorretas;
	
	public void crearFlota(){
		flota.add(new Flota());
	}
	
	public void avazarTurno() {
		
		this.personas = this.personas + this.velocidadCrecimiento;
		
		if(aumentandoProduccion)
			this.velocidadProduccion++;

		if(produciendoNaveDeBatalla)
			for(int i=0; i < velocidadProduccion;i++)
				flota.get(0).crearNaveDeBatalla();

		if(produciendoNaveDestructor)
			for(int i=0; i < velocidadProduccion;i++)
				flota.get(0).crearNaveDestructor();

		if(produciendoNaveDeTransporte)
			for(int i=0; i < velocidadProduccion;i++)
				flota.get(0).crearNaveDeTransporte();

		
		if(produciendoTorretas)
			for(int i=0; i < velocidadProduccion;i++)
				this.cantidadTorretas++;
		
	}
	
	public void aumentarProduccion() {
		this.aumentandoProduccion = true;
		this.produciendoNaveDeBatalla = false;
		this.produciendoNaveDeTransporte = false;
		this.produciendoNaveDestructor = false;
		this.produciendoTorretas = false;
	}
	
	public void producirNavesDeBatalla() {
		this.aumentandoProduccion = false;
		this.produciendoNaveDeBatalla = true;
		this.produciendoNaveDeTransporte = false;
		this.produciendoNaveDestructor = false;
		this.produciendoTorretas = false;
	}
	
	public void producirNaveDeTransporte() {
		this.aumentandoProduccion = false;
		this.produciendoNaveDeBatalla = false;
		this.produciendoNaveDeTransporte = true;
		this.produciendoNaveDestructor = false;
		this.produciendoTorretas = false;		
	}
	
	public void producirNaveDestructor() {
		this.aumentandoProduccion = false;
		this.produciendoNaveDeBatalla = false;
		this.produciendoNaveDeTransporte = false;
		this.produciendoNaveDestructor = true;
		this.produciendoTorretas = false;		
	}
	
	public void producirTorretas() {
		this.aumentandoProduccion = false;
		this.produciendoNaveDeBatalla = false;
		this.produciendoNaveDeTransporte = false;
		this.produciendoNaveDestructor = false;
		this.produciendoTorretas = true;
	}

	public boolean isAumentandoProduccion() {
		return aumentandoProduccion;
	}

	public boolean isProduciendoNaveDeBatalla() {
		return produciendoNaveDeBatalla;
	}

	public boolean isProduciendoNaveDeTransporte() {
		return produciendoNaveDeTransporte;
	}

	public boolean isProduciendoNaveDestructor() {
		return produciendoNaveDestructor;
	}

	public boolean isProduciendoTorretas() {
		return produciendoTorretas;
	}

	public void setProduciendoTorretas(boolean produciendoTorretas) {
		this.produciendoTorretas = produciendoTorretas;
	}

	public int getCantidadTorretas() {
		return cantidadTorretas;
	}

	public int getVelocidadCrecimiento() {
		return velocidadCrecimiento;
	}

	public int getVelocidadProduccion() {
		return velocidadProduccion;
	}
	
	
}
