//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Posicion.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//


package modelo;

public class Posicion {
	private float x;
	private float y;
}
