//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Transporte.java
//  @ Date : 11/05/2017
//  @ Author : 
//
//


package modelo;

public class Transporte extends Nave {
}
